# Generated by Django 4.1.2 on 2022-10-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='colour',
            old_name='colour',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model',
            new_name='title',
        ),
    ]
