# Generated by Django 4.1.2 on 2022-10-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_brand_brand_title_rename_colour_colour_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='title',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='colour',
            old_name='title',
            new_name='colour',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='title',
            new_name='model',
        ),
    ]
