# Generated by Django 4.1.2 on 2022-10-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rename_title_brand_brand_rename_title_colour_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
